### ISSUE TITLE
Readme needs update - development graphs are no longer supported

### ISSUE THREAD

**Issue by d3rp3tt3** [apollographql/supergraph-demo-fed2#265]
The readme for the project shows a screenshot and some text that tells you to select a deployed graph. Since development graphs are no longer a thing in Studio in place of sandbox, the Studio UI modal dialog is now different. 

Changes needed
* Update the Studio UI screenshot for creating a graph to the latest UI
* Update the procedure text on creating a new graph to remove any reference to multiple graph types - there are only deployed graphs now

**Comment by prasek** [comment]
Thanks @d3rp3tt3 will do an update on this! 👍

**Comment by prasek** [comment]
Fixed with the latest docs 🙏
