### ISSUE TITLE
Apollo Client is no longer showing any results in the client/defer-ac demo app

### ISSUE THREAD

**Issue by jpvajda** [apollographql/supergraph-demo-fed2#277]
### Steps to repro 

1. clone https://github.com/apollographql/supergraph-demo-fed2/pull/276
2.  follow the steps provided in the [PR](https://github.com/apollographql/supergraph-demo-fed2/pull/276) to run the fed 2 demo
3. see that no results appear in the web client demo app. 😢

**Comment by prasek** [comment]
this is working now per
- https://github.com/apollographql/supergraph-demo-fed2/pull/276
