### ISSUE TITLE
Reviews service does not work with `rover dev`

### ISSUE THREAD

**Issue by prasek** [apollographql/supergraph-demo-fed2#283]
Reviews service does not work with `rover dev`
```
rover dev --name reviews --url http://localhost:4005
would you like to watch ./supergraph.graphql for changes instead of introspecting every second? [Y/n]
n
watching 'reviews' subgraph for changes...
polling http://localhost:4005/ every 1 second
error: could not run `rover graph introspect --endpoint http://localhost:4005/` or `rover subgraph introspect --endpoint http://localhost:4005/`
        error[E004]: HTTP status client error (404 Not Found) for url (http://localhost:4005/)
        This error was unexpected! Please submit an issue with any relevant details about what you were trying to do: https://github.com/apollographql/rover/issues/new/choose

notifying main `rover dev` session about removed subgraph 'reviews'
```

Using instructions from:
- https://github.com/apollographql/rover/pull/1190

This works with Apollo Server subgraphs using `_service` introspection for dynamic composition done by `rover dev`
```
make docker-up-subgraphs-localhost

rover dev --name products --url http://localhost:4001
```

However the **reviews service** does not support the following query
```
query {
  _service {
    sdl
  }
}
```

With a response of `404 Not Found`

**Comment by patrick91** [comment]
@prasek I think it might be because the reviews subgraph exposes the API at `/graphql`: https://github.com/apollographql/supergraph-demo-fed2/blob/main/subgraphs/reviews/app.py#L12

**Comment by EverlastingBugstopper** [comment]
is the introspection endpoint at `http://localhost:4005/graphql` instead of just `http://localhost:4005`? i'm suprised it's returning a 404 here. you need to be able to run `rover graph introspect` or `rover subgraph introspect` against whatever endpoint unless you have a local schema file to watch.

**Comment by prasek** [comment]
ah, thanks for that. Apollo Server handles this better so it was confusing when the Kotlin and Python subgraphs weren't responding in a similar fashion.

Like the idea of: https://github.com/apollographql/rover/issues/1310
