### ISSUE TITLE
Inventory service does not work with `rover dev`

### ISSUE THREAD

**Issue by prasek** [apollographql/supergraph-demo-fed2#284]
Inventory service does not work with `rover dev`
```
rover dev --name inventory --url http://localhost:4002
would you like to watch ./supergraph.graphql for changes instead of introspecting every second? [Y/n]
n
watching 'inventory' subgraph for changes...
polling http://localhost:4002/ every 1 second
error: could not run `rover graph introspect --endpoint http://localhost:4002/` or `rover subgraph introspect --endpoint http://localhost:4002/`
        error[E004]: HTTP status client error (404 Not Found) for url (http://localhost:4002/)
        This error was unexpected! Please submit an issue with any relevant details about what you were trying to do: https://github.com/apollographql/rover/issues/new/choose

notifying main `rover dev` session about removed subgraph 'inventory'
```

Using instructions from:
- https://github.com/apollographql/rover/pull/1190

This works with Apollo Server subgraphs using `_service` introspection for dynamic composition done by `rover dev`
```
make docker-up-subgraphs-localhost

rover dev --name products --url http://localhost:4001
```

However the **inventory service** does not support the following query
```
query {
  _service {
    sdl
  }
}
```

With a response of `404 Not Found`:
```
{
    "timestamp": "2022-09-13T17:37:21.738+00:00",
    "status": 404,
    "error": "Not Found",
    "path": "/"
}
```

So when trying to

**Comment by EverlastingBugstopper** [comment]
again, this is likely to be because the introspection endpoint is at `/graphql` instead of the root.

**Comment by prasek** [comment]
ah, thanks for that. Apollo Server handles this better so it was confusing when the Kotlin and Python subgraphs weren't responding in a similar fashion.

Like the idea of: https://github.com/apollographql/rover/issues/1310
